### ISSUE TITLE
show/hide field

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#216]
I have understood how to code the yaml file to show/hide a field depending on the value of another field of the form.

But is it possible to show a field depending on a variable value?

I have tried showOnlyIf just with value false to test if it was working but nothing happened. The field is still visible with that configuration.

This is what I would like in users form:

```yaml
    gsQRCode:
      title: _('QR Code')
      showOnlyIf: ${company.hasFeature(Features::QRCODE)}
      type: select
      defautlValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("No")
          '1':
            title: _("Yes")
      info:
        type: box
        position: left
        icon: help
        text: _("Add QR Code to user portal to provision GS Wave mobile softphone")
        label: _("Need help?")
```
